# Generated by Django 3.1.6 on 2021-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
    ]
