# Generated by Django 3.1.6 on 2021-04-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_billing',
        ),
    ]
